name: Release New Version

on:
  workflow_call:
    inputs:
      releaseSettingsPath:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  release-new-version:
    name: Releasing new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.token }}
      - name: Creating Release
        uses: cangulo-actions/cangulo.nuke.releasecreator@v0.0.1
        with:
          releaseSettingsPath: ${{ inputs.releaseSettingsPath }}
          token: ${{ secrets.token }}