name: Validating Commits

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]


jobs:
  call-validate-commits-workflow:
    name: Validating Commits
    uses: cangulo-actions/workflows/.github/workflows/validate-commits.yml@main
    with:
      validationSettingsPath: ./cicd/prCommitValidationSettings.json