name: Release New Version

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [main]


jobs:
  call-release-new-version-workflow:
    name: Releasing new version
    uses: cangulo-actions/workflows/.github/workflows/release-new-version.yml@main
    with:
      releaseSettingsPath: ./cicd/releaseSettings.json
    secrets:
      token: ${{ secrets.ACCESS_PUBLIC_REPOS }}